package com.example.clinicapp.network;

public enum MessageType {
    LOGIN,
    LOGOUT,
    BOOK_APPOINTMENT,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    APPOINTMENT_NOTIFICATION,
    GET_APPOINTMENTS_FOR_DOCTOR,
    APPOINTMENT_LIST,
    SAVE_RECIPE,
    RECIPE_SAVED,
    RECIPE_SAVE_FAILED,

    // Doctor related messages
    REGISTER_DOCTOR,
    DOCTOR_REGISTERED,
    DOCTOR_REGISTER_FAILED,
    GET_ALL_DOCTORS,
    ALL_DOCTORS_LIST,
    CHECK_DOCTOR_EMAIL_EXISTS,
    DOCTOR_EMAIL_EXISTS_RESULT,
    DOCTOR_LOGIN,
    DOCTOR_LOGIN_SUCCESS,
    DOCTOR_LOGIN_FAILED,

    // Patient related messages
    REGISTER_PATIENT,
    PATIENT_REGISTERED,
    PATIENT_REGISTER_FAILED,
    GET_ALL_PATIENTS,
    ALL_PATIENTS_LIST,
    PATIENT_LOGIN,
    PATIENT_LOGIN_SUCCESS,
    PATIENT_LOGIN_FAILED,

    // Recipe related messages
    GET_RECIPES_FOR_PATIENT,
    PATIENT_RECIPES_LIST,

    // Statistics related messages
    GET_PATIENTS_LAST_7_DAYS,
    PATIENTS_LAST_7_DAYS_DATA
}
