package com.example.clinicapp.network;

public enum MessageType {
    LOGIN,
    LOGOUT,
    BOOK_APPOINTMENT,
    BOOKING_CONFIRMED,
    BOOKING_CANCELLED,
    APPOINTMENT_NOTIFICATION,
    GET_APPOINTMENTS_FOR_DOCTOR,
    APPOINTMENT_LIST,
    SAVE_RECIPE,
    RECIPE_SAVED,
    RECIPE_SAVE_FAILED
}